all: testfabric testvenachain testplatone testplaton
	
testfabric:
	make -C fabric all

testvenachain:
	make -C venachain all

testplatone:
	make -C platone all

testplaton:
	make -C platon all

clean:
	make -C fabric clean
	make -C venachain clean
	make -C platone clean