/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: peer/lifecycle/lifecycle.proto */

#ifndef PROTOBUF_C_peer_2flifecycle_2flifecycle_2eproto__INCLUDED
#define PROTOBUF_C_peer_2flifecycle_2flifecycle_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Lifecycle__InstallChaincodeArgs Lifecycle__InstallChaincodeArgs;
typedef struct _Lifecycle__InstallChaincodeResult Lifecycle__InstallChaincodeResult;
typedef struct _Lifecycle__QueryInstalledChaincodeArgs Lifecycle__QueryInstalledChaincodeArgs;
typedef struct _Lifecycle__QueryInstalledChaincodeResult Lifecycle__QueryInstalledChaincodeResult;


/* --- enums --- */


/* --- messages --- */

/*
 * InstallChaincodeArgs is the message used as the argument to
 * '+lifecycle.InstallChaincode'
 */
struct  _Lifecycle__InstallChaincodeArgs
{
  ProtobufCMessage base;
  char *name;
  char *version;
  /*
   * This should be a marshaled peer.ChaincodeInstallPackage
   */
  protobuf_c_boolean has_chaincode_install_package;
  ProtobufCBinaryData chaincode_install_package;
};
#define LIFECYCLE__INSTALL_CHAINCODE_ARGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lifecycle__install_chaincode_args__descriptor) \
    , NULL, NULL, 0,{0,NULL} }


/*
 * InstallChaincodeArgs is the message returned by
 * '+lifecycle.InstallChaincode'
 */
struct  _Lifecycle__InstallChaincodeResult
{
  ProtobufCMessage base;
  protobuf_c_boolean has_hash;
  ProtobufCBinaryData hash;
};
#define LIFECYCLE__INSTALL_CHAINCODE_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lifecycle__install_chaincode_result__descriptor) \
    , 0,{0,NULL} }


/*
 * QueryInstalledChaincodeArgs is the message returned by
 * '+lifecycle.QueryInstalledChaincode'
 */
struct  _Lifecycle__QueryInstalledChaincodeArgs
{
  ProtobufCMessage base;
  char *name;
  char *version;
};
#define LIFECYCLE__QUERY_INSTALLED_CHAINCODE_ARGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lifecycle__query_installed_chaincode_args__descriptor) \
    , NULL, NULL }


/*
 * QueryInstalledChaincodeResult is the message returned by
 * '+lifecycle.QueryInstalledChaincode'
 */
struct  _Lifecycle__QueryInstalledChaincodeResult
{
  ProtobufCMessage base;
  protobuf_c_boolean has_hash;
  ProtobufCBinaryData hash;
};
#define LIFECYCLE__QUERY_INSTALLED_CHAINCODE_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lifecycle__query_installed_chaincode_result__descriptor) \
    , 0,{0,NULL} }


/* Lifecycle__InstallChaincodeArgs methods */
void   lifecycle__install_chaincode_args__init
                     (Lifecycle__InstallChaincodeArgs         *message);
size_t lifecycle__install_chaincode_args__get_packed_size
                     (const Lifecycle__InstallChaincodeArgs   *message);
size_t lifecycle__install_chaincode_args__pack
                     (const Lifecycle__InstallChaincodeArgs   *message,
                      uint8_t             *out);
size_t lifecycle__install_chaincode_args__pack_to_buffer
                     (const Lifecycle__InstallChaincodeArgs   *message,
                      ProtobufCBuffer     *buffer);
Lifecycle__InstallChaincodeArgs *
       lifecycle__install_chaincode_args__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lifecycle__install_chaincode_args__free_unpacked
                     (Lifecycle__InstallChaincodeArgs *message,
                      ProtobufCAllocator *allocator);
/* Lifecycle__InstallChaincodeResult methods */
void   lifecycle__install_chaincode_result__init
                     (Lifecycle__InstallChaincodeResult         *message);
size_t lifecycle__install_chaincode_result__get_packed_size
                     (const Lifecycle__InstallChaincodeResult   *message);
size_t lifecycle__install_chaincode_result__pack
                     (const Lifecycle__InstallChaincodeResult   *message,
                      uint8_t             *out);
size_t lifecycle__install_chaincode_result__pack_to_buffer
                     (const Lifecycle__InstallChaincodeResult   *message,
                      ProtobufCBuffer     *buffer);
Lifecycle__InstallChaincodeResult *
       lifecycle__install_chaincode_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lifecycle__install_chaincode_result__free_unpacked
                     (Lifecycle__InstallChaincodeResult *message,
                      ProtobufCAllocator *allocator);
/* Lifecycle__QueryInstalledChaincodeArgs methods */
void   lifecycle__query_installed_chaincode_args__init
                     (Lifecycle__QueryInstalledChaincodeArgs         *message);
size_t lifecycle__query_installed_chaincode_args__get_packed_size
                     (const Lifecycle__QueryInstalledChaincodeArgs   *message);
size_t lifecycle__query_installed_chaincode_args__pack
                     (const Lifecycle__QueryInstalledChaincodeArgs   *message,
                      uint8_t             *out);
size_t lifecycle__query_installed_chaincode_args__pack_to_buffer
                     (const Lifecycle__QueryInstalledChaincodeArgs   *message,
                      ProtobufCBuffer     *buffer);
Lifecycle__QueryInstalledChaincodeArgs *
       lifecycle__query_installed_chaincode_args__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lifecycle__query_installed_chaincode_args__free_unpacked
                     (Lifecycle__QueryInstalledChaincodeArgs *message,
                      ProtobufCAllocator *allocator);
/* Lifecycle__QueryInstalledChaincodeResult methods */
void   lifecycle__query_installed_chaincode_result__init
                     (Lifecycle__QueryInstalledChaincodeResult         *message);
size_t lifecycle__query_installed_chaincode_result__get_packed_size
                     (const Lifecycle__QueryInstalledChaincodeResult   *message);
size_t lifecycle__query_installed_chaincode_result__pack
                     (const Lifecycle__QueryInstalledChaincodeResult   *message,
                      uint8_t             *out);
size_t lifecycle__query_installed_chaincode_result__pack_to_buffer
                     (const Lifecycle__QueryInstalledChaincodeResult   *message,
                      ProtobufCBuffer     *buffer);
Lifecycle__QueryInstalledChaincodeResult *
       lifecycle__query_installed_chaincode_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lifecycle__query_installed_chaincode_result__free_unpacked
                     (Lifecycle__QueryInstalledChaincodeResult *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Lifecycle__InstallChaincodeArgs_Closure)
                 (const Lifecycle__InstallChaincodeArgs *message,
                  void *closure_data);
typedef void (*Lifecycle__InstallChaincodeResult_Closure)
                 (const Lifecycle__InstallChaincodeResult *message,
                  void *closure_data);
typedef void (*Lifecycle__QueryInstalledChaincodeArgs_Closure)
                 (const Lifecycle__QueryInstalledChaincodeArgs *message,
                  void *closure_data);
typedef void (*Lifecycle__QueryInstalledChaincodeResult_Closure)
                 (const Lifecycle__QueryInstalledChaincodeResult *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor lifecycle__install_chaincode_args__descriptor;
extern const ProtobufCMessageDescriptor lifecycle__install_chaincode_result__descriptor;
extern const ProtobufCMessageDescriptor lifecycle__query_installed_chaincode_args__descriptor;
extern const ProtobufCMessageDescriptor lifecycle__query_installed_chaincode_result__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_peer_2flifecycle_2flifecycle_2eproto__INCLUDED */
