/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: consensus/consensus.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "consensus/consensus.pb-c.h"
void   consensus__verify_result__txs_rw_set_entry__init
                     (Consensus__VerifyResult__TxsRwSetEntry         *message)
{
  static const Consensus__VerifyResult__TxsRwSetEntry init_value = CONSENSUS__VERIFY_RESULT__TXS_RW_SET_ENTRY__INIT;
  *message = init_value;
}
void   consensus__verify_result__init
                     (Consensus__VerifyResult         *message)
{
  static const Consensus__VerifyResult init_value = CONSENSUS__VERIFY_RESULT__INIT;
  *message = init_value;
}
size_t consensus__verify_result__get_packed_size
                     (const Consensus__VerifyResult *message)
{
  assert(message->base.descriptor == &consensus__verify_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t consensus__verify_result__pack
                     (const Consensus__VerifyResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &consensus__verify_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t consensus__verify_result__pack_to_buffer
                     (const Consensus__VerifyResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &consensus__verify_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Consensus__VerifyResult *
       consensus__verify_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Consensus__VerifyResult *)
     protobuf_c_message_unpack (&consensus__verify_result__descriptor,
                                allocator, len, data);
}
void   consensus__verify_result__free_unpacked
                     (Consensus__VerifyResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &consensus__verify_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   consensus__proposal_block__txs_rw_set_entry__init
                     (Consensus__ProposalBlock__TxsRwSetEntry         *message)
{
  static const Consensus__ProposalBlock__TxsRwSetEntry init_value = CONSENSUS__PROPOSAL_BLOCK__TXS_RW_SET_ENTRY__INIT;
  *message = init_value;
}
void   consensus__proposal_block__init
                     (Consensus__ProposalBlock         *message)
{
  static const Consensus__ProposalBlock init_value = CONSENSUS__PROPOSAL_BLOCK__INIT;
  *message = init_value;
}
size_t consensus__proposal_block__get_packed_size
                     (const Consensus__ProposalBlock *message)
{
  assert(message->base.descriptor == &consensus__proposal_block__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t consensus__proposal_block__pack
                     (const Consensus__ProposalBlock *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &consensus__proposal_block__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t consensus__proposal_block__pack_to_buffer
                     (const Consensus__ProposalBlock *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &consensus__proposal_block__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Consensus__ProposalBlock *
       consensus__proposal_block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Consensus__ProposalBlock *)
     protobuf_c_message_unpack (&consensus__proposal_block__descriptor,
                                allocator, len, data);
}
void   consensus__proposal_block__free_unpacked
                     (Consensus__ProposalBlock *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &consensus__proposal_block__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   consensus__block_header_consensus_args__init
                     (Consensus__BlockHeaderConsensusArgs         *message)
{
  static const Consensus__BlockHeaderConsensusArgs init_value = CONSENSUS__BLOCK_HEADER_CONSENSUS_ARGS__INIT;
  *message = init_value;
}
size_t consensus__block_header_consensus_args__get_packed_size
                     (const Consensus__BlockHeaderConsensusArgs *message)
{
  assert(message->base.descriptor == &consensus__block_header_consensus_args__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t consensus__block_header_consensus_args__pack
                     (const Consensus__BlockHeaderConsensusArgs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &consensus__block_header_consensus_args__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t consensus__block_header_consensus_args__pack_to_buffer
                     (const Consensus__BlockHeaderConsensusArgs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &consensus__block_header_consensus_args__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Consensus__BlockHeaderConsensusArgs *
       consensus__block_header_consensus_args__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Consensus__BlockHeaderConsensusArgs *)
     protobuf_c_message_unpack (&consensus__block_header_consensus_args__descriptor,
                                allocator, len, data);
}
void   consensus__block_header_consensus_args__free_unpacked
                     (Consensus__BlockHeaderConsensusArgs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &consensus__block_header_consensus_args__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   consensus__governance_member__init
                     (Consensus__GovernanceMember         *message)
{
  static const Consensus__GovernanceMember init_value = CONSENSUS__GOVERNANCE_MEMBER__INIT;
  *message = init_value;
}
size_t consensus__governance_member__get_packed_size
                     (const Consensus__GovernanceMember *message)
{
  assert(message->base.descriptor == &consensus__governance_member__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t consensus__governance_member__pack
                     (const Consensus__GovernanceMember *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &consensus__governance_member__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t consensus__governance_member__pack_to_buffer
                     (const Consensus__GovernanceMember *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &consensus__governance_member__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Consensus__GovernanceMember *
       consensus__governance_member__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Consensus__GovernanceMember *)
     protobuf_c_message_unpack (&consensus__governance_member__descriptor,
                                allocator, len, data);
}
void   consensus__governance_member__free_unpacked
                     (Consensus__GovernanceMember *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &consensus__governance_member__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   consensus__governance_contract__init
                     (Consensus__GovernanceContract         *message)
{
  static const Consensus__GovernanceContract init_value = CONSENSUS__GOVERNANCE_CONTRACT__INIT;
  *message = init_value;
}
size_t consensus__governance_contract__get_packed_size
                     (const Consensus__GovernanceContract *message)
{
  assert(message->base.descriptor == &consensus__governance_contract__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t consensus__governance_contract__pack
                     (const Consensus__GovernanceContract *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &consensus__governance_contract__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t consensus__governance_contract__pack_to_buffer
                     (const Consensus__GovernanceContract *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &consensus__governance_contract__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Consensus__GovernanceContract *
       consensus__governance_contract__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Consensus__GovernanceContract *)
     protobuf_c_message_unpack (&consensus__governance_contract__descriptor,
                                allocator, len, data);
}
void   consensus__governance_contract__free_unpacked
                     (Consensus__GovernanceContract *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &consensus__governance_contract__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor consensus__verify_result__txs_rw_set_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Consensus__VerifyResult__TxsRwSetEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Consensus__VerifyResult__TxsRwSetEntry, value),
    &common__tx_rwset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned consensus__verify_result__txs_rw_set_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange consensus__verify_result__txs_rw_set_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor consensus__verify_result__txs_rw_set_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "consensus.VerifyResult.TxsRwSetEntry",
  "TxsRwSetEntry",
  "Consensus__VerifyResult__TxsRwSetEntry",
  "consensus",
  sizeof(Consensus__VerifyResult__TxsRwSetEntry),
  2,
  consensus__verify_result__txs_rw_set_entry__field_descriptors,
  consensus__verify_result__txs_rw_set_entry__field_indices_by_name,
  1,  consensus__verify_result__txs_rw_set_entry__number_ranges,
  (ProtobufCMessageInit) consensus__verify_result__txs_rw_set_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue consensus__verify_result__code__enum_values_by_number[2] =
{
  { "SUCCESS", "CONSENSUS__VERIFY_RESULT__CODE__SUCCESS", 0 },
  { "FAIL", "CONSENSUS__VERIFY_RESULT__CODE__FAIL", 1 },
};
static const ProtobufCIntRange consensus__verify_result__code__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex consensus__verify_result__code__enum_values_by_name[2] =
{
  { "FAIL", 1 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor consensus__verify_result__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "consensus.VerifyResult.Code",
  "Code",
  "Consensus__VerifyResult__Code",
  "consensus",
  2,
  consensus__verify_result__code__enum_values_by_number,
  2,
  consensus__verify_result__code__enum_values_by_name,
  1,
  consensus__verify_result__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor consensus__verify_result__field_descriptors[4] =
{
  {
    "verified_block",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Consensus__VerifyResult, verified_block),
    &common__block__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Consensus__VerifyResult, code),
    &consensus__verify_result__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Consensus__VerifyResult, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txs_rw_set",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Consensus__VerifyResult, n_txs_rw_set),
    offsetof(Consensus__VerifyResult, txs_rw_set),
    &consensus__verify_result__txs_rw_set_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned consensus__verify_result__field_indices_by_name[] = {
  1,   /* field[1] = code */
  2,   /* field[2] = msg */
  3,   /* field[3] = txs_rw_set */
  0,   /* field[0] = verified_block */
};
static const ProtobufCIntRange consensus__verify_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor consensus__verify_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "consensus.VerifyResult",
  "VerifyResult",
  "Consensus__VerifyResult",
  "consensus",
  sizeof(Consensus__VerifyResult),
  4,
  consensus__verify_result__field_descriptors,
  consensus__verify_result__field_indices_by_name,
  1,  consensus__verify_result__number_ranges,
  (ProtobufCMessageInit) consensus__verify_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor consensus__proposal_block__txs_rw_set_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Consensus__ProposalBlock__TxsRwSetEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Consensus__ProposalBlock__TxsRwSetEntry, value),
    &common__tx_rwset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned consensus__proposal_block__txs_rw_set_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange consensus__proposal_block__txs_rw_set_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor consensus__proposal_block__txs_rw_set_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "consensus.ProposalBlock.TxsRwSetEntry",
  "TxsRwSetEntry",
  "Consensus__ProposalBlock__TxsRwSetEntry",
  "consensus",
  sizeof(Consensus__ProposalBlock__TxsRwSetEntry),
  2,
  consensus__proposal_block__txs_rw_set_entry__field_descriptors,
  consensus__proposal_block__txs_rw_set_entry__field_indices_by_name,
  1,  consensus__proposal_block__txs_rw_set_entry__number_ranges,
  (ProtobufCMessageInit) consensus__proposal_block__txs_rw_set_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor consensus__proposal_block__field_descriptors[2] =
{
  {
    "block",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Consensus__ProposalBlock, block),
    &common__block__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txs_rw_set",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Consensus__ProposalBlock, n_txs_rw_set),
    offsetof(Consensus__ProposalBlock, txs_rw_set),
    &consensus__proposal_block__txs_rw_set_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned consensus__proposal_block__field_indices_by_name[] = {
  0,   /* field[0] = block */
  1,   /* field[1] = txs_rw_set */
};
static const ProtobufCIntRange consensus__proposal_block__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor consensus__proposal_block__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "consensus.ProposalBlock",
  "ProposalBlock",
  "Consensus__ProposalBlock",
  "consensus",
  sizeof(Consensus__ProposalBlock),
  2,
  consensus__proposal_block__field_descriptors,
  consensus__proposal_block__field_indices_by_name,
  1,  consensus__proposal_block__number_ranges,
  (ProtobufCMessageInit) consensus__proposal_block__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor consensus__block_header_consensus_args__field_descriptors[4] =
{
  {
    "ConsensusType",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__BlockHeaderConsensusArgs, consensustype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Round",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__BlockHeaderConsensusArgs, round),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Level",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__BlockHeaderConsensusArgs, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ConsensusData",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Consensus__BlockHeaderConsensusArgs, consensusdata),
    &common__tx_rwset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned consensus__block_header_consensus_args__field_indices_by_name[] = {
  3,   /* field[3] = ConsensusData */
  0,   /* field[0] = ConsensusType */
  2,   /* field[2] = Level */
  1,   /* field[1] = Round */
};
static const ProtobufCIntRange consensus__block_header_consensus_args__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor consensus__block_header_consensus_args__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "consensus.BlockHeaderConsensusArgs",
  "BlockHeaderConsensusArgs",
  "Consensus__BlockHeaderConsensusArgs",
  "consensus",
  sizeof(Consensus__BlockHeaderConsensusArgs),
  4,
  consensus__block_header_consensus_args__field_descriptors,
  consensus__block_header_consensus_args__field_indices_by_name,
  2,  consensus__block_header_consensus_args__number_ranges,
  (ProtobufCMessageInit) consensus__block_header_consensus_args__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor consensus__governance_member__field_descriptors[2] =
{
  {
    "NodeID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceMember, nodeid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Index",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceMember, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned consensus__governance_member__field_indices_by_name[] = {
  1,   /* field[1] = Index */
  0,   /* field[0] = NodeID */
};
static const ProtobufCIntRange consensus__governance_member__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor consensus__governance_member__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "consensus.GovernanceMember",
  "GovernanceMember",
  "Consensus__GovernanceMember",
  "consensus",
  sizeof(Consensus__GovernanceMember),
  2,
  consensus__governance_member__field_descriptors,
  consensus__governance_member__field_indices_by_name,
  1,  consensus__governance_member__number_ranges,
  (ProtobufCMessageInit) consensus__governance_member__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor consensus__governance_contract__field_descriptors[19] =
{
  {
    "EpochId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, epochid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, type),
    &consensus__consensus_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CurMaxIndex",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, curmaxindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SkipTimeoutCommit",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, skiptimeoutcommit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ConfigSequence",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, configsequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "N",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MinQuorumForQc",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, minquorumforqc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CachedLen",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, cachedlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "NextSwitchHeight",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, nextswitchheight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TransitBlock",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, transitblock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "BlockNumPerEpoch",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, blocknumperepoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ValidatorNum",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, validatornum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "NodeProposeRound",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, nodeproposeround),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Members",
    15,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Consensus__GovernanceContract, n_members),
    offsetof(Consensus__GovernanceContract, members),
    &consensus__governance_member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Validators",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Consensus__GovernanceContract, n_validators),
    offsetof(Consensus__GovernanceContract, validators),
    &consensus__governance_member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "NextValidators",
    17,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Consensus__GovernanceContract, n_nextvalidators),
    offsetof(Consensus__GovernanceContract, nextvalidators),
    &consensus__governance_member__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LastMinQuorumForQc",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, lastminquorumforqc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HotstuffRoundTimeoutMill",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, hotstuffroundtimeoutmill),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "HotstuffRoundTimeoutIntervalMill",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Consensus__GovernanceContract, hotstuffroundtimeoutintervalmill),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned consensus__governance_contract__field_indices_by_name[] = {
  10,   /* field[10] = BlockNumPerEpoch */
  7,   /* field[7] = CachedLen */
  4,   /* field[4] = ConfigSequence */
  2,   /* field[2] = CurMaxIndex */
  0,   /* field[0] = EpochId */
  18,   /* field[18] = HotstuffRoundTimeoutIntervalMill */
  17,   /* field[17] = HotstuffRoundTimeoutMill */
  16,   /* field[16] = LastMinQuorumForQc */
  13,   /* field[13] = Members */
  6,   /* field[6] = MinQuorumForQc */
  5,   /* field[5] = N */
  8,   /* field[8] = NextSwitchHeight */
  15,   /* field[15] = NextValidators */
  12,   /* field[12] = NodeProposeRound */
  3,   /* field[3] = SkipTimeoutCommit */
  9,   /* field[9] = TransitBlock */
  1,   /* field[1] = Type */
  11,   /* field[11] = ValidatorNum */
  14,   /* field[14] = Validators */
};
static const ProtobufCIntRange consensus__governance_contract__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor consensus__governance_contract__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "consensus.GovernanceContract",
  "GovernanceContract",
  "Consensus__GovernanceContract",
  "consensus",
  sizeof(Consensus__GovernanceContract),
  19,
  consensus__governance_contract__field_descriptors,
  consensus__governance_contract__field_indices_by_name,
  2,  consensus__governance_contract__number_ranges,
  (ProtobufCMessageInit) consensus__governance_contract__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue consensus__consensus_type__enum_values_by_number[7] =
{
  { "SOLO", "CONSENSUS__CONSENSUS_TYPE__SOLO", 0 },
  { "TBFT", "CONSENSUS__CONSENSUS_TYPE__TBFT", 1 },
  { "MBFT", "CONSENSUS__CONSENSUS_TYPE__MBFT", 2 },
  { "HOTSTUFF", "CONSENSUS__CONSENSUS_TYPE__HOTSTUFF", 3 },
  { "RAFT", "CONSENSUS__CONSENSUS_TYPE__RAFT", 4 },
  { "DPOS", "CONSENSUS__CONSENSUS_TYPE__DPOS", 5 },
  { "POW", "CONSENSUS__CONSENSUS_TYPE__POW", 10 },
};
static const ProtobufCIntRange consensus__consensus_type__value_ranges[] = {
{0, 0},{10, 6},{0, 7}
};
static const ProtobufCEnumValueIndex consensus__consensus_type__enum_values_by_name[7] =
{
  { "DPOS", 5 },
  { "HOTSTUFF", 3 },
  { "MBFT", 2 },
  { "POW", 6 },
  { "RAFT", 4 },
  { "SOLO", 0 },
  { "TBFT", 1 },
};
const ProtobufCEnumDescriptor consensus__consensus_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "consensus.ConsensusType",
  "ConsensusType",
  "Consensus__ConsensusType",
  "consensus",
  7,
  consensus__consensus_type__enum_values_by_number,
  7,
  consensus__consensus_type__enum_values_by_name,
  2,
  consensus__consensus_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
