/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: store/store.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "store/store.pb-c.h"
void   store__serialized_block__init
                     (Store__SerializedBlock         *message)
{
  static const Store__SerializedBlock init_value = STORE__SERIALIZED_BLOCK__INIT;
  *message = init_value;
}
size_t store__serialized_block__get_packed_size
                     (const Store__SerializedBlock *message)
{
  assert(message->base.descriptor == &store__serialized_block__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t store__serialized_block__pack
                     (const Store__SerializedBlock *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &store__serialized_block__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t store__serialized_block__pack_to_buffer
                     (const Store__SerializedBlock *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &store__serialized_block__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Store__SerializedBlock *
       store__serialized_block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Store__SerializedBlock *)
     protobuf_c_message_unpack (&store__serialized_block__descriptor,
                                allocator, len, data);
}
void   store__serialized_block__free_unpacked
                     (Store__SerializedBlock *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &store__serialized_block__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   store__block_with_rwset__init
                     (Store__BlockWithRWSet         *message)
{
  static const Store__BlockWithRWSet init_value = STORE__BLOCK_WITH_RWSET__INIT;
  *message = init_value;
}
size_t store__block_with_rwset__get_packed_size
                     (const Store__BlockWithRWSet *message)
{
  assert(message->base.descriptor == &store__block_with_rwset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t store__block_with_rwset__pack
                     (const Store__BlockWithRWSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &store__block_with_rwset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t store__block_with_rwset__pack_to_buffer
                     (const Store__BlockWithRWSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &store__block_with_rwset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Store__BlockWithRWSet *
       store__block_with_rwset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Store__BlockWithRWSet *)
     protobuf_c_message_unpack (&store__block_with_rwset__descriptor,
                                allocator, len, data);
}
void   store__block_with_rwset__free_unpacked
                     (Store__BlockWithRWSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &store__block_with_rwset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor store__serialized_block__field_descriptors[4] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Store__SerializedBlock, header),
    &common__block_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dag",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Store__SerializedBlock, dag),
    &common__dag__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_ids",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Store__SerializedBlock, n_tx_ids),
    offsetof(Store__SerializedBlock, tx_ids),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "additional_data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Store__SerializedBlock, additional_data),
    &common__additional_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned store__serialized_block__field_indices_by_name[] = {
  3,   /* field[3] = additional_data */
  1,   /* field[1] = dag */
  0,   /* field[0] = header */
  2,   /* field[2] = tx_ids */
};
static const ProtobufCIntRange store__serialized_block__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor store__serialized_block__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "store.SerializedBlock",
  "SerializedBlock",
  "Store__SerializedBlock",
  "store",
  sizeof(Store__SerializedBlock),
  4,
  store__serialized_block__field_descriptors,
  store__serialized_block__field_indices_by_name,
  1,  store__serialized_block__number_ranges,
  (ProtobufCMessageInit) store__serialized_block__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor store__block_with_rwset__field_descriptors[3] =
{
  {
    "block",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Store__BlockWithRWSet, block),
    &common__block__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txRWSets",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Store__BlockWithRWSet, n_txrwsets),
    offsetof(Store__BlockWithRWSet, txrwsets),
    &common__tx_rwset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contract_events",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Store__BlockWithRWSet, n_contract_events),
    offsetof(Store__BlockWithRWSet, contract_events),
    &common__contract_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned store__block_with_rwset__field_indices_by_name[] = {
  0,   /* field[0] = block */
  2,   /* field[2] = contract_events */
  1,   /* field[1] = txRWSets */
};
static const ProtobufCIntRange store__block_with_rwset__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor store__block_with_rwset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "store.BlockWithRWSet",
  "BlockWithRWSet",
  "Store__BlockWithRWSet",
  "store",
  sizeof(Store__BlockWithRWSet),
  3,
  store__block_with_rwset__field_descriptors,
  store__block_with_rwset__field_indices_by_name,
  1,  store__block_with_rwset__number_ranges,
  (ProtobufCMessageInit) store__block_with_rwset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue store__db_type__enum_values_by_number[8] =
{
  { "INVALID_DB", "STORE__DB_TYPE__INVALID_DB", 0 },
  { "BLOCK_DB", "STORE__DB_TYPE__BLOCK_DB", 1 },
  { "BLOCK_INDEX_DB", "STORE__DB_TYPE__BLOCK_INDEX_DB", 2 },
  { "TX_DB", "STORE__DB_TYPE__TX_DB", 3 },
  { "TX_INDEX_DB", "STORE__DB_TYPE__TX_INDEX_DB", 4 },
  { "SOFT_DB", "STORE__DB_TYPE__SOFT_DB", 5 },
  { "STATE_DB", "STORE__DB_TYPE__STATE_DB", 6 },
  { "READ_WRITE_DB", "STORE__DB_TYPE__READ_WRITE_DB", 7 },
};
static const ProtobufCIntRange store__db_type__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex store__db_type__enum_values_by_name[8] =
{
  { "BLOCK_DB", 1 },
  { "BLOCK_INDEX_DB", 2 },
  { "INVALID_DB", 0 },
  { "READ_WRITE_DB", 7 },
  { "SOFT_DB", 5 },
  { "STATE_DB", 6 },
  { "TX_DB", 3 },
  { "TX_INDEX_DB", 4 },
};
const ProtobufCEnumDescriptor store__db_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "store.DbType",
  "DbType",
  "Store__DbType",
  "store",
  8,
  store__db_type__enum_values_by_number,
  8,
  store__db_type__enum_values_by_name,
  1,
  store__db_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
