/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common/block.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "common/block.pb-c.h"
void   common__block__init
                     (Common__Block         *message)
{
  static const Common__Block init_value = COMMON__BLOCK__INIT;
  *message = init_value;
}
size_t common__block__get_packed_size
                     (const Common__Block *message)
{
  assert(message->base.descriptor == &common__block__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t common__block__pack
                     (const Common__Block *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &common__block__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t common__block__pack_to_buffer
                     (const Common__Block *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &common__block__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Common__Block *
       common__block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Common__Block *)
     protobuf_c_message_unpack (&common__block__descriptor,
                                allocator, len, data);
}
void   common__block__free_unpacked
                     (Common__Block *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &common__block__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   common__block_info__init
                     (Common__BlockInfo         *message)
{
  static const Common__BlockInfo init_value = COMMON__BLOCK_INFO__INIT;
  *message = init_value;
}
size_t common__block_info__get_packed_size
                     (const Common__BlockInfo *message)
{
  assert(message->base.descriptor == &common__block_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t common__block_info__pack
                     (const Common__BlockInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &common__block_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t common__block_info__pack_to_buffer
                     (const Common__BlockInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &common__block_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Common__BlockInfo *
       common__block_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Common__BlockInfo *)
     protobuf_c_message_unpack (&common__block_info__descriptor,
                                allocator, len, data);
}
void   common__block_info__free_unpacked
                     (Common__BlockInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &common__block_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   common__additional_data__extra_data_entry__init
                     (Common__AdditionalData__ExtraDataEntry         *message)
{
  static const Common__AdditionalData__ExtraDataEntry init_value = COMMON__ADDITIONAL_DATA__EXTRA_DATA_ENTRY__INIT;
  *message = init_value;
}
void   common__additional_data__init
                     (Common__AdditionalData         *message)
{
  static const Common__AdditionalData init_value = COMMON__ADDITIONAL_DATA__INIT;
  *message = init_value;
}
size_t common__additional_data__get_packed_size
                     (const Common__AdditionalData *message)
{
  assert(message->base.descriptor == &common__additional_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t common__additional_data__pack
                     (const Common__AdditionalData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &common__additional_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t common__additional_data__pack_to_buffer
                     (const Common__AdditionalData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &common__additional_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Common__AdditionalData *
       common__additional_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Common__AdditionalData *)
     protobuf_c_message_unpack (&common__additional_data__descriptor,
                                allocator, len, data);
}
void   common__additional_data__free_unpacked
                     (Common__AdditionalData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &common__additional_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   common__block_header__init
                     (Common__BlockHeader         *message)
{
  static const Common__BlockHeader init_value = COMMON__BLOCK_HEADER__INIT;
  *message = init_value;
}
size_t common__block_header__get_packed_size
                     (const Common__BlockHeader *message)
{
  assert(message->base.descriptor == &common__block_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t common__block_header__pack
                     (const Common__BlockHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &common__block_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t common__block_header__pack_to_buffer
                     (const Common__BlockHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &common__block_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Common__BlockHeader *
       common__block_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Common__BlockHeader *)
     protobuf_c_message_unpack (&common__block_header__descriptor,
                                allocator, len, data);
}
void   common__block_header__free_unpacked
                     (Common__BlockHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &common__block_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   common__dag__neighbor__init
                     (Common__DAG__Neighbor         *message)
{
  static const Common__DAG__Neighbor init_value = COMMON__DAG__NEIGHBOR__INIT;
  *message = init_value;
}
void   common__dag__init
                     (Common__DAG         *message)
{
  static const Common__DAG init_value = COMMON__DAG__INIT;
  *message = init_value;
}
size_t common__dag__get_packed_size
                     (const Common__DAG *message)
{
  assert(message->base.descriptor == &common__dag__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t common__dag__pack
                     (const Common__DAG *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &common__dag__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t common__dag__pack_to_buffer
                     (const Common__DAG *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &common__dag__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Common__DAG *
       common__dag__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Common__DAG *)
     protobuf_c_message_unpack (&common__dag__descriptor,
                                allocator, len, data);
}
void   common__dag__free_unpacked
                     (Common__DAG *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &common__dag__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor common__block__field_descriptors[4] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Common__Block, header),
    &common__block_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dag",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Common__Block, dag),
    &common__dag__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Common__Block, n_txs),
    offsetof(Common__Block, txs),
    &common__transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "additional_data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Common__Block, additional_data),
    &common__additional_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned common__block__field_indices_by_name[] = {
  3,   /* field[3] = additional_data */
  1,   /* field[1] = dag */
  0,   /* field[0] = header */
  2,   /* field[2] = txs */
};
static const ProtobufCIntRange common__block__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor common__block__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "common.Block",
  "Block",
  "Common__Block",
  "common",
  sizeof(Common__Block),
  4,
  common__block__field_descriptors,
  common__block__field_indices_by_name,
  1,  common__block__number_ranges,
  (ProtobufCMessageInit) common__block__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor common__block_info__field_descriptors[2] =
{
  {
    "block",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Common__BlockInfo, block),
    &common__block__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rwset_list",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Common__BlockInfo, n_rwset_list),
    offsetof(Common__BlockInfo, rwset_list),
    &common__tx_rwset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned common__block_info__field_indices_by_name[] = {
  0,   /* field[0] = block */
  1,   /* field[1] = rwset_list */
};
static const ProtobufCIntRange common__block_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor common__block_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "common.BlockInfo",
  "BlockInfo",
  "Common__BlockInfo",
  "common",
  sizeof(Common__BlockInfo),
  2,
  common__block_info__field_descriptors,
  common__block_info__field_indices_by_name,
  1,  common__block_info__number_ranges,
  (ProtobufCMessageInit) common__block_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor common__additional_data__extra_data_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Common__AdditionalData__ExtraDataEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Common__AdditionalData__ExtraDataEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned common__additional_data__extra_data_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange common__additional_data__extra_data_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor common__additional_data__extra_data_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "common.AdditionalData.ExtraDataEntry",
  "ExtraDataEntry",
  "Common__AdditionalData__ExtraDataEntry",
  "common",
  sizeof(Common__AdditionalData__ExtraDataEntry),
  2,
  common__additional_data__extra_data_entry__field_descriptors,
  common__additional_data__extra_data_entry__field_indices_by_name,
  1,  common__additional_data__extra_data_entry__number_ranges,
  (ProtobufCMessageInit) common__additional_data__extra_data_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor common__additional_data__field_descriptors[1] =
{
  {
    "extra_data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Common__AdditionalData, n_extra_data),
    offsetof(Common__AdditionalData, extra_data),
    &common__additional_data__extra_data_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned common__additional_data__field_indices_by_name[] = {
  0,   /* field[0] = extra_data */
};
static const ProtobufCIntRange common__additional_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor common__additional_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "common.AdditionalData",
  "AdditionalData",
  "Common__AdditionalData",
  "common",
  sizeof(Common__AdditionalData),
  1,
  common__additional_data__field_descriptors,
  common__additional_data__field_indices_by_name,
  1,  common__additional_data__number_ranges,
  (ProtobufCMessageInit) common__additional_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor common__block_header__field_descriptors[14] =
{
  {
    "chain_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, chain_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block_height",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, block_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pre_block_hash",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, pre_block_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block_hash",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, block_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pre_conf_height",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, pre_conf_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block_version",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, block_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dag_hash",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, dag_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rw_set_root",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, rw_set_root),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_root",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, tx_root),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block_timestamp",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, block_timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proposer",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, proposer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "consensus_args",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, consensus_args),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_count",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, tx_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Common__BlockHeader, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned common__block_header__field_indices_by_name[] = {
  3,   /* field[3] = block_hash */
  1,   /* field[1] = block_height */
  9,   /* field[9] = block_timestamp */
  5,   /* field[5] = block_version */
  0,   /* field[0] = chain_id */
  11,   /* field[11] = consensus_args */
  6,   /* field[6] = dag_hash */
  2,   /* field[2] = pre_block_hash */
  4,   /* field[4] = pre_conf_height */
  10,   /* field[10] = proposer */
  7,   /* field[7] = rw_set_root */
  13,   /* field[13] = signature */
  12,   /* field[12] = tx_count */
  8,   /* field[8] = tx_root */
};
static const ProtobufCIntRange common__block_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor common__block_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "common.BlockHeader",
  "BlockHeader",
  "Common__BlockHeader",
  "common",
  sizeof(Common__BlockHeader),
  14,
  common__block_header__field_descriptors,
  common__block_header__field_indices_by_name,
  1,  common__block_header__number_ranges,
  (ProtobufCMessageInit) common__block_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor common__dag__neighbor__field_descriptors[1] =
{
  {
    "neighbors",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Common__DAG__Neighbor, n_neighbors),
    offsetof(Common__DAG__Neighbor, neighbors),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned common__dag__neighbor__field_indices_by_name[] = {
  0,   /* field[0] = neighbors */
};
static const ProtobufCIntRange common__dag__neighbor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor common__dag__neighbor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "common.DAG.Neighbor",
  "Neighbor",
  "Common__DAG__Neighbor",
  "common",
  sizeof(Common__DAG__Neighbor),
  1,
  common__dag__neighbor__field_descriptors,
  common__dag__neighbor__field_indices_by_name,
  1,  common__dag__neighbor__number_ranges,
  (ProtobufCMessageInit) common__dag__neighbor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor common__dag__field_descriptors[1] =
{
  {
    "vertexes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Common__DAG, n_vertexes),
    offsetof(Common__DAG, vertexes),
    &common__dag__neighbor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned common__dag__field_indices_by_name[] = {
  0,   /* field[0] = vertexes */
};
static const ProtobufCIntRange common__dag__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor common__dag__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "common.DAG",
  "DAG",
  "Common__DAG",
  "common",
  sizeof(Common__DAG),
  1,
  common__dag__field_descriptors,
  common__dag__field_indices_by_name,
  1,  common__dag__number_ranges,
  (ProtobufCMessageInit) common__dag__init,
  NULL,NULL,NULL    /* reserved[123] */
};
