/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: accesscontrol/member.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "member.pb-c.h"
void   accesscontrol__serialized_member__init
                     (Accesscontrol__SerializedMember         *message)
{
  static const Accesscontrol__SerializedMember init_value = ACCESSCONTROL__SERIALIZED_MEMBER__INIT;
  *message = init_value;
}
size_t accesscontrol__serialized_member__get_packed_size
                     (const Accesscontrol__SerializedMember *message)
{
  assert(message->base.descriptor == &accesscontrol__serialized_member__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t accesscontrol__serialized_member__pack
                     (const Accesscontrol__SerializedMember *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &accesscontrol__serialized_member__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t accesscontrol__serialized_member__pack_to_buffer
                     (const Accesscontrol__SerializedMember *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &accesscontrol__serialized_member__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Accesscontrol__SerializedMember *
       accesscontrol__serialized_member__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Accesscontrol__SerializedMember *)
     protobuf_c_message_unpack (&accesscontrol__serialized_member__descriptor,
                                allocator, len, data);
}
void   accesscontrol__serialized_member__free_unpacked
                     (Accesscontrol__SerializedMember *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &accesscontrol__serialized_member__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor accesscontrol__serialized_member__field_descriptors[3] =
{
  {
    "org_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accesscontrol__SerializedMember, org_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "member_info",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Accesscontrol__SerializedMember, member_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_full_cert",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Accesscontrol__SerializedMember, is_full_cert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned accesscontrol__serialized_member__field_indices_by_name[] = {
  2,   /* field[2] = is_full_cert */
  1,   /* field[1] = member_info */
  0,   /* field[0] = org_id */
};
static const ProtobufCIntRange accesscontrol__serialized_member__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor accesscontrol__serialized_member__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "accesscontrol.SerializedMember",
  "SerializedMember",
  "Accesscontrol__SerializedMember",
  "accesscontrol",
  sizeof(Accesscontrol__SerializedMember),
  3,
  accesscontrol__serialized_member__field_descriptors,
  accesscontrol__serialized_member__field_indices_by_name,
  1,  accesscontrol__serialized_member__number_ranges,
  (ProtobufCMessageInit) accesscontrol__serialized_member__init,
  NULL,NULL,NULL    /* reserved[123] */
};
