/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: orderer/etcdraft/configuration.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "orderer/etcdraft/configuration.pb-c.h"
void   etcdraft__metadata__init
                     (Etcdraft__Metadata         *message)
{
  static Etcdraft__Metadata init_value = ETCDRAFT__METADATA__INIT;
  *message = init_value;
}
size_t etcdraft__metadata__get_packed_size
                     (const Etcdraft__Metadata *message)
{
  assert(message->base.descriptor == &etcdraft__metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t etcdraft__metadata__pack
                     (const Etcdraft__Metadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &etcdraft__metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t etcdraft__metadata__pack_to_buffer
                     (const Etcdraft__Metadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &etcdraft__metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Etcdraft__Metadata *
       etcdraft__metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Etcdraft__Metadata *)
     protobuf_c_message_unpack (&etcdraft__metadata__descriptor,
                                allocator, len, data);
}
void   etcdraft__metadata__free_unpacked
                     (Etcdraft__Metadata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &etcdraft__metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   etcdraft__consenter__init
                     (Etcdraft__Consenter         *message)
{
  static Etcdraft__Consenter init_value = ETCDRAFT__CONSENTER__INIT;
  *message = init_value;
}
size_t etcdraft__consenter__get_packed_size
                     (const Etcdraft__Consenter *message)
{
  assert(message->base.descriptor == &etcdraft__consenter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t etcdraft__consenter__pack
                     (const Etcdraft__Consenter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &etcdraft__consenter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t etcdraft__consenter__pack_to_buffer
                     (const Etcdraft__Consenter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &etcdraft__consenter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Etcdraft__Consenter *
       etcdraft__consenter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Etcdraft__Consenter *)
     protobuf_c_message_unpack (&etcdraft__consenter__descriptor,
                                allocator, len, data);
}
void   etcdraft__consenter__free_unpacked
                     (Etcdraft__Consenter *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &etcdraft__consenter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   etcdraft__options__init
                     (Etcdraft__Options         *message)
{
  static Etcdraft__Options init_value = ETCDRAFT__OPTIONS__INIT;
  *message = init_value;
}
size_t etcdraft__options__get_packed_size
                     (const Etcdraft__Options *message)
{
  assert(message->base.descriptor == &etcdraft__options__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t etcdraft__options__pack
                     (const Etcdraft__Options *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &etcdraft__options__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t etcdraft__options__pack_to_buffer
                     (const Etcdraft__Options *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &etcdraft__options__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Etcdraft__Options *
       etcdraft__options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Etcdraft__Options *)
     protobuf_c_message_unpack (&etcdraft__options__descriptor,
                                allocator, len, data);
}
void   etcdraft__options__free_unpacked
                     (Etcdraft__Options *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &etcdraft__options__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   etcdraft__raft_metadata__consenters_entry__init
                     (Etcdraft__RaftMetadata__ConsentersEntry         *message)
{
  static Etcdraft__RaftMetadata__ConsentersEntry init_value = ETCDRAFT__RAFT_METADATA__CONSENTERS_ENTRY__INIT;
  *message = init_value;
}
void   etcdraft__raft_metadata__init
                     (Etcdraft__RaftMetadata         *message)
{
  static Etcdraft__RaftMetadata init_value = ETCDRAFT__RAFT_METADATA__INIT;
  *message = init_value;
}
size_t etcdraft__raft_metadata__get_packed_size
                     (const Etcdraft__RaftMetadata *message)
{
  assert(message->base.descriptor == &etcdraft__raft_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t etcdraft__raft_metadata__pack
                     (const Etcdraft__RaftMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &etcdraft__raft_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t etcdraft__raft_metadata__pack_to_buffer
                     (const Etcdraft__RaftMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &etcdraft__raft_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Etcdraft__RaftMetadata *
       etcdraft__raft_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Etcdraft__RaftMetadata *)
     protobuf_c_message_unpack (&etcdraft__raft_metadata__descriptor,
                                allocator, len, data);
}
void   etcdraft__raft_metadata__free_unpacked
                     (Etcdraft__RaftMetadata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &etcdraft__raft_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor etcdraft__metadata__field_descriptors[2] =
{
  {
    "consenters",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Etcdraft__Metadata, n_consenters),
    offsetof(Etcdraft__Metadata, consenters),
    &etcdraft__consenter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "options",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Etcdraft__Metadata, options),
    &etcdraft__options__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned etcdraft__metadata__field_indices_by_name[] = {
  0,   /* field[0] = consenters */
  1,   /* field[1] = options */
};
static const ProtobufCIntRange etcdraft__metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor etcdraft__metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "etcdraft.Metadata",
  "Metadata",
  "Etcdraft__Metadata",
  "etcdraft",
  sizeof(Etcdraft__Metadata),
  2,
  etcdraft__metadata__field_descriptors,
  etcdraft__metadata__field_indices_by_name,
  1,  etcdraft__metadata__number_ranges,
  (ProtobufCMessageInit) etcdraft__metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor etcdraft__consenter__field_descriptors[4] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Etcdraft__Consenter, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Etcdraft__Consenter, has_port),
    offsetof(Etcdraft__Consenter, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_tls_cert",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Etcdraft__Consenter, has_client_tls_cert),
    offsetof(Etcdraft__Consenter, client_tls_cert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_tls_cert",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Etcdraft__Consenter, has_server_tls_cert),
    offsetof(Etcdraft__Consenter, server_tls_cert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned etcdraft__consenter__field_indices_by_name[] = {
  2,   /* field[2] = client_tls_cert */
  0,   /* field[0] = host */
  1,   /* field[1] = port */
  3,   /* field[3] = server_tls_cert */
};
static const ProtobufCIntRange etcdraft__consenter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor etcdraft__consenter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "etcdraft.Consenter",
  "Consenter",
  "Etcdraft__Consenter",
  "etcdraft",
  sizeof(Etcdraft__Consenter),
  4,
  etcdraft__consenter__field_descriptors,
  etcdraft__consenter__field_indices_by_name,
  1,  etcdraft__consenter__number_ranges,
  (ProtobufCMessageInit) etcdraft__consenter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor etcdraft__options__field_descriptors[6] =
{
  {
    "tick_interval",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Etcdraft__Options, has_tick_interval),
    offsetof(Etcdraft__Options, tick_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "election_tick",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Etcdraft__Options, has_election_tick),
    offsetof(Etcdraft__Options, election_tick),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeat_tick",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Etcdraft__Options, has_heartbeat_tick),
    offsetof(Etcdraft__Options, heartbeat_tick),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_inflight_msgs",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Etcdraft__Options, has_max_inflight_msgs),
    offsetof(Etcdraft__Options, max_inflight_msgs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_size_per_msg",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Etcdraft__Options, has_max_size_per_msg),
    offsetof(Etcdraft__Options, max_size_per_msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "snapshot_interval",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Etcdraft__Options, has_snapshot_interval),
    offsetof(Etcdraft__Options, snapshot_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned etcdraft__options__field_indices_by_name[] = {
  1,   /* field[1] = election_tick */
  2,   /* field[2] = heartbeat_tick */
  3,   /* field[3] = max_inflight_msgs */
  4,   /* field[4] = max_size_per_msg */
  5,   /* field[5] = snapshot_interval */
  0,   /* field[0] = tick_interval */
};
static const ProtobufCIntRange etcdraft__options__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor etcdraft__options__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "etcdraft.Options",
  "Options",
  "Etcdraft__Options",
  "etcdraft",
  sizeof(Etcdraft__Options),
  6,
  etcdraft__options__field_descriptors,
  etcdraft__options__field_indices_by_name,
  1,  etcdraft__options__number_ranges,
  (ProtobufCMessageInit) etcdraft__options__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor etcdraft__raft_metadata__consenters_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Etcdraft__RaftMetadata__ConsentersEntry, has_key),
    offsetof(Etcdraft__RaftMetadata__ConsentersEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Etcdraft__RaftMetadata__ConsentersEntry, value),
    &etcdraft__consenter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned etcdraft__raft_metadata__consenters_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange etcdraft__raft_metadata__consenters_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor etcdraft__raft_metadata__consenters_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "etcdraft.RaftMetadata.ConsentersEntry",
  "ConsentersEntry",
  "Etcdraft__RaftMetadata__ConsentersEntry",
  "etcdraft",
  sizeof(Etcdraft__RaftMetadata__ConsentersEntry),
  2,
  etcdraft__raft_metadata__consenters_entry__field_descriptors,
  etcdraft__raft_metadata__consenters_entry__field_indices_by_name,
  1,  etcdraft__raft_metadata__consenters_entry__number_ranges,
  (ProtobufCMessageInit) etcdraft__raft_metadata__consenters_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor etcdraft__raft_metadata__field_descriptors[4] =
{
  {
    "consenters",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Etcdraft__RaftMetadata, n_consenters),
    offsetof(Etcdraft__RaftMetadata, consenters),
    &etcdraft__raft_metadata__consenters_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next_consenter_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Etcdraft__RaftMetadata, has_next_consenter_id),
    offsetof(Etcdraft__RaftMetadata, next_consenter_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_change_counts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Etcdraft__RaftMetadata, has_conf_change_counts),
    offsetof(Etcdraft__RaftMetadata, conf_change_counts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "raft_index",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Etcdraft__RaftMetadata, has_raft_index),
    offsetof(Etcdraft__RaftMetadata, raft_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned etcdraft__raft_metadata__field_indices_by_name[] = {
  2,   /* field[2] = conf_change_counts */
  0,   /* field[0] = consenters */
  1,   /* field[1] = next_consenter_id */
  3,   /* field[3] = raft_index */
};
static const ProtobufCIntRange etcdraft__raft_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor etcdraft__raft_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "etcdraft.RaftMetadata",
  "RaftMetadata",
  "Etcdraft__RaftMetadata",
  "etcdraft",
  sizeof(Etcdraft__RaftMetadata),
  4,
  etcdraft__raft_metadata__field_descriptors,
  etcdraft__raft_metadata__field_indices_by_name,
  1,  etcdraft__raft_metadata__number_ranges,
  (ProtobufCMessageInit) etcdraft__raft_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
