/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: token/expectations.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "token/expectations.pb-c.h"
void   protos__token_expectation__init
                     (Protos__TokenExpectation         *message)
{
  static Protos__TokenExpectation init_value = PROTOS__TOKEN_EXPECTATION__INIT;
  *message = init_value;
}
size_t protos__token_expectation__get_packed_size
                     (const Protos__TokenExpectation *message)
{
  assert(message->base.descriptor == &protos__token_expectation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__token_expectation__pack
                     (const Protos__TokenExpectation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__token_expectation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__token_expectation__pack_to_buffer
                     (const Protos__TokenExpectation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__token_expectation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__TokenExpectation *
       protos__token_expectation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__TokenExpectation *)
     protobuf_c_message_unpack (&protos__token_expectation__descriptor,
                                allocator, len, data);
}
void   protos__token_expectation__free_unpacked
                     (Protos__TokenExpectation *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__token_expectation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__plain_expectation__init
                     (Protos__PlainExpectation         *message)
{
  static Protos__PlainExpectation init_value = PROTOS__PLAIN_EXPECTATION__INIT;
  *message = init_value;
}
size_t protos__plain_expectation__get_packed_size
                     (const Protos__PlainExpectation *message)
{
  assert(message->base.descriptor == &protos__plain_expectation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__plain_expectation__pack
                     (const Protos__PlainExpectation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__plain_expectation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__plain_expectation__pack_to_buffer
                     (const Protos__PlainExpectation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__plain_expectation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__PlainExpectation *
       protos__plain_expectation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__PlainExpectation *)
     protobuf_c_message_unpack (&protos__plain_expectation__descriptor,
                                allocator, len, data);
}
void   protos__plain_expectation__free_unpacked
                     (Protos__PlainExpectation *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__plain_expectation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__plain_token_expectation__init
                     (Protos__PlainTokenExpectation         *message)
{
  static Protos__PlainTokenExpectation init_value = PROTOS__PLAIN_TOKEN_EXPECTATION__INIT;
  *message = init_value;
}
size_t protos__plain_token_expectation__get_packed_size
                     (const Protos__PlainTokenExpectation *message)
{
  assert(message->base.descriptor == &protos__plain_token_expectation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__plain_token_expectation__pack
                     (const Protos__PlainTokenExpectation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__plain_token_expectation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__plain_token_expectation__pack_to_buffer
                     (const Protos__PlainTokenExpectation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__plain_token_expectation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__PlainTokenExpectation *
       protos__plain_token_expectation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__PlainTokenExpectation *)
     protobuf_c_message_unpack (&protos__plain_token_expectation__descriptor,
                                allocator, len, data);
}
void   protos__plain_token_expectation__free_unpacked
                     (Protos__PlainTokenExpectation *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__plain_token_expectation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protos__token_expectation__field_descriptors[1] =
{
  {
    "plain_expectation",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protos__TokenExpectation, expectation_case),
    offsetof(Protos__TokenExpectation, plain_expectation),
    &protos__plain_expectation__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__token_expectation__field_indices_by_name[] = {
  0,   /* field[0] = plain_expectation */
};
static const ProtobufCIntRange protos__token_expectation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protos__token_expectation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.TokenExpectation",
  "TokenExpectation",
  "Protos__TokenExpectation",
  "protos",
  sizeof(Protos__TokenExpectation),
  1,
  protos__token_expectation__field_descriptors,
  protos__token_expectation__field_indices_by_name,
  1,  protos__token_expectation__number_ranges,
  (ProtobufCMessageInit) protos__token_expectation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__plain_expectation__field_descriptors[2] =
{
  {
    "import_expectation",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protos__PlainExpectation, payload_case),
    offsetof(Protos__PlainExpectation, import_expectation),
    &protos__plain_token_expectation__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transfer_expectation",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protos__PlainExpectation, payload_case),
    offsetof(Protos__PlainExpectation, transfer_expectation),
    &protos__plain_token_expectation__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__plain_expectation__field_indices_by_name[] = {
  0,   /* field[0] = import_expectation */
  1,   /* field[1] = transfer_expectation */
};
static const ProtobufCIntRange protos__plain_expectation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protos__plain_expectation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.PlainExpectation",
  "PlainExpectation",
  "Protos__PlainExpectation",
  "protos",
  sizeof(Protos__PlainExpectation),
  2,
  protos__plain_expectation__field_descriptors,
  protos__plain_expectation__field_indices_by_name,
  1,  protos__plain_expectation__number_ranges,
  (ProtobufCMessageInit) protos__plain_expectation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__plain_token_expectation__field_descriptors[1] =
{
  {
    "outputs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protos__PlainTokenExpectation, n_outputs),
    offsetof(Protos__PlainTokenExpectation, outputs),
    &plain_output__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__plain_token_expectation__field_indices_by_name[] = {
  0,   /* field[0] = outputs */
};
static const ProtobufCIntRange protos__plain_token_expectation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protos__plain_token_expectation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.PlainTokenExpectation",
  "PlainTokenExpectation",
  "Protos__PlainTokenExpectation",
  "protos",
  sizeof(Protos__PlainTokenExpectation),
  1,
  protos__plain_token_expectation__field_descriptors,
  protos__plain_token_expectation__field_indices_by_name,
  1,  protos__plain_token_expectation__number_ranges,
  (ProtobufCMessageInit) protos__plain_token_expectation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
