/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: orderer/kafka.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "orderer/kafka.pb-c.h"
void   orderer__kafka_message__init
                     (Orderer__KafkaMessage         *message)
{
  static Orderer__KafkaMessage init_value = ORDERER__KAFKA_MESSAGE__INIT;
  *message = init_value;
}
size_t orderer__kafka_message__get_packed_size
                     (const Orderer__KafkaMessage *message)
{
  assert(message->base.descriptor == &orderer__kafka_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orderer__kafka_message__pack
                     (const Orderer__KafkaMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orderer__kafka_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orderer__kafka_message__pack_to_buffer
                     (const Orderer__KafkaMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orderer__kafka_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orderer__KafkaMessage *
       orderer__kafka_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orderer__KafkaMessage *)
     protobuf_c_message_unpack (&orderer__kafka_message__descriptor,
                                allocator, len, data);
}
void   orderer__kafka_message__free_unpacked
                     (Orderer__KafkaMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &orderer__kafka_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orderer__kafka_message_regular__init
                     (Orderer__KafkaMessageRegular         *message)
{
  static Orderer__KafkaMessageRegular init_value = ORDERER__KAFKA_MESSAGE_REGULAR__INIT;
  *message = init_value;
}
size_t orderer__kafka_message_regular__get_packed_size
                     (const Orderer__KafkaMessageRegular *message)
{
  assert(message->base.descriptor == &orderer__kafka_message_regular__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orderer__kafka_message_regular__pack
                     (const Orderer__KafkaMessageRegular *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orderer__kafka_message_regular__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orderer__kafka_message_regular__pack_to_buffer
                     (const Orderer__KafkaMessageRegular *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orderer__kafka_message_regular__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orderer__KafkaMessageRegular *
       orderer__kafka_message_regular__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orderer__KafkaMessageRegular *)
     protobuf_c_message_unpack (&orderer__kafka_message_regular__descriptor,
                                allocator, len, data);
}
void   orderer__kafka_message_regular__free_unpacked
                     (Orderer__KafkaMessageRegular *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &orderer__kafka_message_regular__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orderer__kafka_message_time_to_cut__init
                     (Orderer__KafkaMessageTimeToCut         *message)
{
  static Orderer__KafkaMessageTimeToCut init_value = ORDERER__KAFKA_MESSAGE_TIME_TO_CUT__INIT;
  *message = init_value;
}
size_t orderer__kafka_message_time_to_cut__get_packed_size
                     (const Orderer__KafkaMessageTimeToCut *message)
{
  assert(message->base.descriptor == &orderer__kafka_message_time_to_cut__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orderer__kafka_message_time_to_cut__pack
                     (const Orderer__KafkaMessageTimeToCut *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orderer__kafka_message_time_to_cut__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orderer__kafka_message_time_to_cut__pack_to_buffer
                     (const Orderer__KafkaMessageTimeToCut *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orderer__kafka_message_time_to_cut__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orderer__KafkaMessageTimeToCut *
       orderer__kafka_message_time_to_cut__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orderer__KafkaMessageTimeToCut *)
     protobuf_c_message_unpack (&orderer__kafka_message_time_to_cut__descriptor,
                                allocator, len, data);
}
void   orderer__kafka_message_time_to_cut__free_unpacked
                     (Orderer__KafkaMessageTimeToCut *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &orderer__kafka_message_time_to_cut__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orderer__kafka_message_connect__init
                     (Orderer__KafkaMessageConnect         *message)
{
  static Orderer__KafkaMessageConnect init_value = ORDERER__KAFKA_MESSAGE_CONNECT__INIT;
  *message = init_value;
}
size_t orderer__kafka_message_connect__get_packed_size
                     (const Orderer__KafkaMessageConnect *message)
{
  assert(message->base.descriptor == &orderer__kafka_message_connect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orderer__kafka_message_connect__pack
                     (const Orderer__KafkaMessageConnect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orderer__kafka_message_connect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orderer__kafka_message_connect__pack_to_buffer
                     (const Orderer__KafkaMessageConnect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orderer__kafka_message_connect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orderer__KafkaMessageConnect *
       orderer__kafka_message_connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orderer__KafkaMessageConnect *)
     protobuf_c_message_unpack (&orderer__kafka_message_connect__descriptor,
                                allocator, len, data);
}
void   orderer__kafka_message_connect__free_unpacked
                     (Orderer__KafkaMessageConnect *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &orderer__kafka_message_connect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   orderer__kafka_metadata__init
                     (Orderer__KafkaMetadata         *message)
{
  static Orderer__KafkaMetadata init_value = ORDERER__KAFKA_METADATA__INIT;
  *message = init_value;
}
size_t orderer__kafka_metadata__get_packed_size
                     (const Orderer__KafkaMetadata *message)
{
  assert(message->base.descriptor == &orderer__kafka_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t orderer__kafka_metadata__pack
                     (const Orderer__KafkaMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &orderer__kafka_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t orderer__kafka_metadata__pack_to_buffer
                     (const Orderer__KafkaMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &orderer__kafka_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Orderer__KafkaMetadata *
       orderer__kafka_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Orderer__KafkaMetadata *)
     protobuf_c_message_unpack (&orderer__kafka_metadata__descriptor,
                                allocator, len, data);
}
void   orderer__kafka_metadata__free_unpacked
                     (Orderer__KafkaMetadata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &orderer__kafka_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor orderer__kafka_message__field_descriptors[3] =
{
  {
    "regular",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orderer__KafkaMessage, type_case),
    offsetof(Orderer__KafkaMessage, regular),
    &orderer__kafka_message_regular__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_to_cut",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orderer__KafkaMessage, type_case),
    offsetof(Orderer__KafkaMessage, time_to_cut),
    &orderer__kafka_message_time_to_cut__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connect",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Orderer__KafkaMessage, type_case),
    offsetof(Orderer__KafkaMessage, connect),
    &orderer__kafka_message_connect__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orderer__kafka_message__field_indices_by_name[] = {
  2,   /* field[2] = connect */
  0,   /* field[0] = regular */
  1,   /* field[1] = time_to_cut */
};
static const ProtobufCIntRange orderer__kafka_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor orderer__kafka_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orderer.KafkaMessage",
  "KafkaMessage",
  "Orderer__KafkaMessage",
  "orderer",
  sizeof(Orderer__KafkaMessage),
  3,
  orderer__kafka_message__field_descriptors,
  orderer__kafka_message__field_indices_by_name,
  1,  orderer__kafka_message__number_ranges,
  (ProtobufCMessageInit) orderer__kafka_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue orderer__kafka_message_regular__class__enum_values_by_number[3] =
{
  { "UNKNOWN", "ORDERER__KAFKA_MESSAGE_REGULAR__CLASS__UNKNOWN", 0 },
  { "NORMAL", "ORDERER__KAFKA_MESSAGE_REGULAR__CLASS__NORMAL", 1 },
  { "CONFIG", "ORDERER__KAFKA_MESSAGE_REGULAR__CLASS__CONFIG", 2 },
};
static const ProtobufCIntRange orderer__kafka_message_regular__class__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex orderer__kafka_message_regular__class__enum_values_by_name[3] =
{
  { "CONFIG", 2 },
  { "NORMAL", 1 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor orderer__kafka_message_regular__class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "orderer.KafkaMessageRegular.Class",
  "Class",
  "Orderer__KafkaMessageRegular__Class",
  "orderer",
  3,
  orderer__kafka_message_regular__class__enum_values_by_number,
  3,
  orderer__kafka_message_regular__class__enum_values_by_name,
  1,
  orderer__kafka_message_regular__class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor orderer__kafka_message_regular__field_descriptors[4] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Orderer__KafkaMessageRegular, has_payload),
    offsetof(Orderer__KafkaMessageRegular, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config_seq",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orderer__KafkaMessageRegular, has_config_seq),
    offsetof(Orderer__KafkaMessageRegular, config_seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Orderer__KafkaMessageRegular, has_class_),
    offsetof(Orderer__KafkaMessageRegular, class_),
    &orderer__kafka_message_regular__class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "original_offset",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Orderer__KafkaMessageRegular, has_original_offset),
    offsetof(Orderer__KafkaMessageRegular, original_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orderer__kafka_message_regular__field_indices_by_name[] = {
  2,   /* field[2] = class */
  1,   /* field[1] = config_seq */
  3,   /* field[3] = original_offset */
  0,   /* field[0] = payload */
};
static const ProtobufCIntRange orderer__kafka_message_regular__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor orderer__kafka_message_regular__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orderer.KafkaMessageRegular",
  "KafkaMessageRegular",
  "Orderer__KafkaMessageRegular",
  "orderer",
  sizeof(Orderer__KafkaMessageRegular),
  4,
  orderer__kafka_message_regular__field_descriptors,
  orderer__kafka_message_regular__field_indices_by_name,
  1,  orderer__kafka_message_regular__number_ranges,
  (ProtobufCMessageInit) orderer__kafka_message_regular__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orderer__kafka_message_time_to_cut__field_descriptors[1] =
{
  {
    "block_number",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Orderer__KafkaMessageTimeToCut, has_block_number),
    offsetof(Orderer__KafkaMessageTimeToCut, block_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orderer__kafka_message_time_to_cut__field_indices_by_name[] = {
  0,   /* field[0] = block_number */
};
static const ProtobufCIntRange orderer__kafka_message_time_to_cut__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor orderer__kafka_message_time_to_cut__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orderer.KafkaMessageTimeToCut",
  "KafkaMessageTimeToCut",
  "Orderer__KafkaMessageTimeToCut",
  "orderer",
  sizeof(Orderer__KafkaMessageTimeToCut),
  1,
  orderer__kafka_message_time_to_cut__field_descriptors,
  orderer__kafka_message_time_to_cut__field_indices_by_name,
  1,  orderer__kafka_message_time_to_cut__number_ranges,
  (ProtobufCMessageInit) orderer__kafka_message_time_to_cut__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orderer__kafka_message_connect__field_descriptors[1] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Orderer__KafkaMessageConnect, has_payload),
    offsetof(Orderer__KafkaMessageConnect, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orderer__kafka_message_connect__field_indices_by_name[] = {
  0,   /* field[0] = payload */
};
static const ProtobufCIntRange orderer__kafka_message_connect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor orderer__kafka_message_connect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orderer.KafkaMessageConnect",
  "KafkaMessageConnect",
  "Orderer__KafkaMessageConnect",
  "orderer",
  sizeof(Orderer__KafkaMessageConnect),
  1,
  orderer__kafka_message_connect__field_descriptors,
  orderer__kafka_message_connect__field_indices_by_name,
  1,  orderer__kafka_message_connect__number_ranges,
  (ProtobufCMessageInit) orderer__kafka_message_connect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor orderer__kafka_metadata__field_descriptors[3] =
{
  {
    "last_offset_persisted",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Orderer__KafkaMetadata, has_last_offset_persisted),
    offsetof(Orderer__KafkaMetadata, last_offset_persisted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_original_offset_processed",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Orderer__KafkaMetadata, has_last_original_offset_processed),
    offsetof(Orderer__KafkaMetadata, last_original_offset_processed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_resubmitted_config_offset",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Orderer__KafkaMetadata, has_last_resubmitted_config_offset),
    offsetof(Orderer__KafkaMetadata, last_resubmitted_config_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned orderer__kafka_metadata__field_indices_by_name[] = {
  0,   /* field[0] = last_offset_persisted */
  1,   /* field[1] = last_original_offset_processed */
  2,   /* field[2] = last_resubmitted_config_offset */
};
static const ProtobufCIntRange orderer__kafka_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor orderer__kafka_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "orderer.KafkaMetadata",
  "KafkaMetadata",
  "Orderer__KafkaMetadata",
  "orderer",
  sizeof(Orderer__KafkaMetadata),
  3,
  orderer__kafka_metadata__field_descriptors,
  orderer__kafka_metadata__field_indices_by_name,
  1,  orderer__kafka_metadata__number_ranges,
  (ProtobufCMessageInit) orderer__kafka_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
