/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: peer/chaincode_event.proto */

#ifndef PROTOBUF_C_peer_2fchaincode_5fevent_2eproto__INCLUDED
#define PROTOBUF_C_peer_2fchaincode_5fevent_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Protos__ChaincodeEvent Protos__ChaincodeEvent;


/* --- enums --- */


/* --- messages --- */

/*
 *ChaincodeEvent is used for events and registrations that are specific to chaincode
 *string type - "chaincode"
 */
struct  _Protos__ChaincodeEvent
{
  ProtobufCMessage base;
  char *chaincode_id;
  char *tx_id;
  char *event_name;
  protobuf_c_boolean has_payload;
  ProtobufCBinaryData payload;
};
#define PROTOS__CHAINCODE_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protos__chaincode_event__descriptor) \
    , NULL, NULL, NULL, 0,{0,NULL} }


/* Protos__ChaincodeEvent methods */
void   protos__chaincode_event__init
                     (Protos__ChaincodeEvent         *message);
size_t protos__chaincode_event__get_packed_size
                     (const Protos__ChaincodeEvent   *message);
size_t protos__chaincode_event__pack
                     (const Protos__ChaincodeEvent   *message,
                      uint8_t             *out);
size_t protos__chaincode_event__pack_to_buffer
                     (const Protos__ChaincodeEvent   *message,
                      ProtobufCBuffer     *buffer);
Protos__ChaincodeEvent *
       protos__chaincode_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protos__chaincode_event__free_unpacked
                     (Protos__ChaincodeEvent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protos__ChaincodeEvent_Closure)
                 (const Protos__ChaincodeEvent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protos__chaincode_event__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_peer_2fchaincode_5fevent_2eproto__INCLUDED */
