/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: peer/query.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "peer/query.pb-c.h"
void   protos__chaincode_query_response__init
                     (Protos__ChaincodeQueryResponse         *message)
{
  static Protos__ChaincodeQueryResponse init_value = PROTOS__CHAINCODE_QUERY_RESPONSE__INIT;
  *message = init_value;
}
size_t protos__chaincode_query_response__get_packed_size
                     (const Protos__ChaincodeQueryResponse *message)
{
  assert(message->base.descriptor == &protos__chaincode_query_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__chaincode_query_response__pack
                     (const Protos__ChaincodeQueryResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__chaincode_query_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__chaincode_query_response__pack_to_buffer
                     (const Protos__ChaincodeQueryResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__chaincode_query_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__ChaincodeQueryResponse *
       protos__chaincode_query_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__ChaincodeQueryResponse *)
     protobuf_c_message_unpack (&protos__chaincode_query_response__descriptor,
                                allocator, len, data);
}
void   protos__chaincode_query_response__free_unpacked
                     (Protos__ChaincodeQueryResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__chaincode_query_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__chaincode_info__init
                     (Protos__ChaincodeInfo         *message)
{
  static Protos__ChaincodeInfo init_value = PROTOS__CHAINCODE_INFO__INIT;
  *message = init_value;
}
size_t protos__chaincode_info__get_packed_size
                     (const Protos__ChaincodeInfo *message)
{
  assert(message->base.descriptor == &protos__chaincode_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__chaincode_info__pack
                     (const Protos__ChaincodeInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__chaincode_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__chaincode_info__pack_to_buffer
                     (const Protos__ChaincodeInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__chaincode_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__ChaincodeInfo *
       protos__chaincode_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__ChaincodeInfo *)
     protobuf_c_message_unpack (&protos__chaincode_info__descriptor,
                                allocator, len, data);
}
void   protos__chaincode_info__free_unpacked
                     (Protos__ChaincodeInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__chaincode_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__channel_query_response__init
                     (Protos__ChannelQueryResponse         *message)
{
  static Protos__ChannelQueryResponse init_value = PROTOS__CHANNEL_QUERY_RESPONSE__INIT;
  *message = init_value;
}
size_t protos__channel_query_response__get_packed_size
                     (const Protos__ChannelQueryResponse *message)
{
  assert(message->base.descriptor == &protos__channel_query_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__channel_query_response__pack
                     (const Protos__ChannelQueryResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__channel_query_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__channel_query_response__pack_to_buffer
                     (const Protos__ChannelQueryResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__channel_query_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__ChannelQueryResponse *
       protos__channel_query_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__ChannelQueryResponse *)
     protobuf_c_message_unpack (&protos__channel_query_response__descriptor,
                                allocator, len, data);
}
void   protos__channel_query_response__free_unpacked
                     (Protos__ChannelQueryResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__channel_query_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__channel_info__init
                     (Protos__ChannelInfo         *message)
{
  static Protos__ChannelInfo init_value = PROTOS__CHANNEL_INFO__INIT;
  *message = init_value;
}
size_t protos__channel_info__get_packed_size
                     (const Protos__ChannelInfo *message)
{
  assert(message->base.descriptor == &protos__channel_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__channel_info__pack
                     (const Protos__ChannelInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__channel_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__channel_info__pack_to_buffer
                     (const Protos__ChannelInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__channel_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__ChannelInfo *
       protos__channel_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__ChannelInfo *)
     protobuf_c_message_unpack (&protos__channel_info__descriptor,
                                allocator, len, data);
}
void   protos__channel_info__free_unpacked
                     (Protos__ChannelInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__channel_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protos__chaincode_query_response__field_descriptors[1] =
{
  {
    "chaincodes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protos__ChaincodeQueryResponse, n_chaincodes),
    offsetof(Protos__ChaincodeQueryResponse, chaincodes),
    &protos__chaincode_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__chaincode_query_response__field_indices_by_name[] = {
  0,   /* field[0] = chaincodes */
};
static const ProtobufCIntRange protos__chaincode_query_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protos__chaincode_query_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.ChaincodeQueryResponse",
  "ChaincodeQueryResponse",
  "Protos__ChaincodeQueryResponse",
  "protos",
  sizeof(Protos__ChaincodeQueryResponse),
  1,
  protos__chaincode_query_response__field_descriptors,
  protos__chaincode_query_response__field_indices_by_name,
  1,  protos__chaincode_query_response__number_ranges,
  (ProtobufCMessageInit) protos__chaincode_query_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__chaincode_info__field_descriptors[7] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__ChaincodeInfo, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__ChaincodeInfo, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__ChaincodeInfo, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__ChaincodeInfo, input),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "escc",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__ChaincodeInfo, escc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vscc",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__ChaincodeInfo, vscc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Protos__ChaincodeInfo, has_id),
    offsetof(Protos__ChaincodeInfo, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__chaincode_info__field_indices_by_name[] = {
  4,   /* field[4] = escc */
  6,   /* field[6] = id */
  3,   /* field[3] = input */
  0,   /* field[0] = name */
  2,   /* field[2] = path */
  1,   /* field[1] = version */
  5,   /* field[5] = vscc */
};
static const ProtobufCIntRange protos__chaincode_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor protos__chaincode_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.ChaincodeInfo",
  "ChaincodeInfo",
  "Protos__ChaincodeInfo",
  "protos",
  sizeof(Protos__ChaincodeInfo),
  7,
  protos__chaincode_info__field_descriptors,
  protos__chaincode_info__field_indices_by_name,
  1,  protos__chaincode_info__number_ranges,
  (ProtobufCMessageInit) protos__chaincode_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__channel_query_response__field_descriptors[1] =
{
  {
    "channels",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Protos__ChannelQueryResponse, n_channels),
    offsetof(Protos__ChannelQueryResponse, channels),
    &protos__channel_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__channel_query_response__field_indices_by_name[] = {
  0,   /* field[0] = channels */
};
static const ProtobufCIntRange protos__channel_query_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protos__channel_query_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.ChannelQueryResponse",
  "ChannelQueryResponse",
  "Protos__ChannelQueryResponse",
  "protos",
  sizeof(Protos__ChannelQueryResponse),
  1,
  protos__channel_query_response__field_descriptors,
  protos__channel_query_response__field_indices_by_name,
  1,  protos__channel_query_response__number_ranges,
  (ProtobufCMessageInit) protos__channel_query_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__channel_info__field_descriptors[1] =
{
  {
    "channel_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__ChannelInfo, channel_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__channel_info__field_indices_by_name[] = {
  0,   /* field[0] = channel_id */
};
static const ProtobufCIntRange protos__channel_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protos__channel_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.ChannelInfo",
  "ChannelInfo",
  "Protos__ChannelInfo",
  "protos",
  sizeof(Protos__ChannelInfo),
  1,
  protos__channel_info__field_descriptors,
  protos__channel_info__field_indices_by_name,
  1,  protos__channel_info__number_ranges,
  (ProtobufCMessageInit) protos__channel_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
