/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: peer/resources.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "peer/resources.pb-c.h"
void   protos__chaincode_identifier__init
                     (Protos__ChaincodeIdentifier         *message)
{
  static Protos__ChaincodeIdentifier init_value = PROTOS__CHAINCODE_IDENTIFIER__INIT;
  *message = init_value;
}
size_t protos__chaincode_identifier__get_packed_size
                     (const Protos__ChaincodeIdentifier *message)
{
  assert(message->base.descriptor == &protos__chaincode_identifier__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__chaincode_identifier__pack
                     (const Protos__ChaincodeIdentifier *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__chaincode_identifier__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__chaincode_identifier__pack_to_buffer
                     (const Protos__ChaincodeIdentifier *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__chaincode_identifier__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__ChaincodeIdentifier *
       protos__chaincode_identifier__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__ChaincodeIdentifier *)
     protobuf_c_message_unpack (&protos__chaincode_identifier__descriptor,
                                allocator, len, data);
}
void   protos__chaincode_identifier__free_unpacked
                     (Protos__ChaincodeIdentifier *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__chaincode_identifier__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__chaincode_validation__init
                     (Protos__ChaincodeValidation         *message)
{
  static Protos__ChaincodeValidation init_value = PROTOS__CHAINCODE_VALIDATION__INIT;
  *message = init_value;
}
size_t protos__chaincode_validation__get_packed_size
                     (const Protos__ChaincodeValidation *message)
{
  assert(message->base.descriptor == &protos__chaincode_validation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__chaincode_validation__pack
                     (const Protos__ChaincodeValidation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__chaincode_validation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__chaincode_validation__pack_to_buffer
                     (const Protos__ChaincodeValidation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__chaincode_validation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__ChaincodeValidation *
       protos__chaincode_validation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__ChaincodeValidation *)
     protobuf_c_message_unpack (&protos__chaincode_validation__descriptor,
                                allocator, len, data);
}
void   protos__chaincode_validation__free_unpacked
                     (Protos__ChaincodeValidation *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__chaincode_validation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__vsccargs__init
                     (Protos__VSCCArgs         *message)
{
  static Protos__VSCCArgs init_value = PROTOS__VSCCARGS__INIT;
  *message = init_value;
}
size_t protos__vsccargs__get_packed_size
                     (const Protos__VSCCArgs *message)
{
  assert(message->base.descriptor == &protos__vsccargs__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__vsccargs__pack
                     (const Protos__VSCCArgs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__vsccargs__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__vsccargs__pack_to_buffer
                     (const Protos__VSCCArgs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__vsccargs__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__VSCCArgs *
       protos__vsccargs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__VSCCArgs *)
     protobuf_c_message_unpack (&protos__vsccargs__descriptor,
                                allocator, len, data);
}
void   protos__vsccargs__free_unpacked
                     (Protos__VSCCArgs *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__vsccargs__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__chaincode_endorsement__init
                     (Protos__ChaincodeEndorsement         *message)
{
  static Protos__ChaincodeEndorsement init_value = PROTOS__CHAINCODE_ENDORSEMENT__INIT;
  *message = init_value;
}
size_t protos__chaincode_endorsement__get_packed_size
                     (const Protos__ChaincodeEndorsement *message)
{
  assert(message->base.descriptor == &protos__chaincode_endorsement__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__chaincode_endorsement__pack
                     (const Protos__ChaincodeEndorsement *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__chaincode_endorsement__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__chaincode_endorsement__pack_to_buffer
                     (const Protos__ChaincodeEndorsement *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__chaincode_endorsement__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__ChaincodeEndorsement *
       protos__chaincode_endorsement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__ChaincodeEndorsement *)
     protobuf_c_message_unpack (&protos__chaincode_endorsement__descriptor,
                                allocator, len, data);
}
void   protos__chaincode_endorsement__free_unpacked
                     (Protos__ChaincodeEndorsement *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__chaincode_endorsement__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protos__config_tree__init
                     (Protos__ConfigTree         *message)
{
  static Protos__ConfigTree init_value = PROTOS__CONFIG_TREE__INIT;
  *message = init_value;
}
size_t protos__config_tree__get_packed_size
                     (const Protos__ConfigTree *message)
{
  assert(message->base.descriptor == &protos__config_tree__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protos__config_tree__pack
                     (const Protos__ConfigTree *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protos__config_tree__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protos__config_tree__pack_to_buffer
                     (const Protos__ConfigTree *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protos__config_tree__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protos__ConfigTree *
       protos__config_tree__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protos__ConfigTree *)
     protobuf_c_message_unpack (&protos__config_tree__descriptor,
                                allocator, len, data);
}
void   protos__config_tree__free_unpacked
                     (Protos__ConfigTree *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &protos__config_tree__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protos__chaincode_identifier__field_descriptors[2] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Protos__ChaincodeIdentifier, has_hash),
    offsetof(Protos__ChaincodeIdentifier, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__ChaincodeIdentifier, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__chaincode_identifier__field_indices_by_name[] = {
  0,   /* field[0] = hash */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange protos__chaincode_identifier__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protos__chaincode_identifier__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.ChaincodeIdentifier",
  "ChaincodeIdentifier",
  "Protos__ChaincodeIdentifier",
  "protos",
  sizeof(Protos__ChaincodeIdentifier),
  2,
  protos__chaincode_identifier__field_descriptors,
  protos__chaincode_identifier__field_indices_by_name,
  1,  protos__chaincode_identifier__number_ranges,
  (ProtobufCMessageInit) protos__chaincode_identifier__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__chaincode_validation__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__ChaincodeValidation, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "argument",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Protos__ChaincodeValidation, has_argument),
    offsetof(Protos__ChaincodeValidation, argument),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__chaincode_validation__field_indices_by_name[] = {
  1,   /* field[1] = argument */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange protos__chaincode_validation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protos__chaincode_validation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.ChaincodeValidation",
  "ChaincodeValidation",
  "Protos__ChaincodeValidation",
  "protos",
  sizeof(Protos__ChaincodeValidation),
  2,
  protos__chaincode_validation__field_descriptors,
  protos__chaincode_validation__field_indices_by_name,
  1,  protos__chaincode_validation__number_ranges,
  (ProtobufCMessageInit) protos__chaincode_validation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__vsccargs__field_descriptors[1] =
{
  {
    "endorsement_policy_ref",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__VSCCArgs, endorsement_policy_ref),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__vsccargs__field_indices_by_name[] = {
  0,   /* field[0] = endorsement_policy_ref */
};
static const ProtobufCIntRange protos__vsccargs__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protos__vsccargs__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.VSCCArgs",
  "VSCCArgs",
  "Protos__VSCCArgs",
  "protos",
  sizeof(Protos__VSCCArgs),
  1,
  protos__vsccargs__field_descriptors,
  protos__vsccargs__field_indices_by_name,
  1,  protos__vsccargs__number_ranges,
  (ProtobufCMessageInit) protos__vsccargs__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__chaincode_endorsement__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Protos__ChaincodeEndorsement, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__chaincode_endorsement__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange protos__chaincode_endorsement__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protos__chaincode_endorsement__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.ChaincodeEndorsement",
  "ChaincodeEndorsement",
  "Protos__ChaincodeEndorsement",
  "protos",
  sizeof(Protos__ChaincodeEndorsement),
  1,
  protos__chaincode_endorsement__field_descriptors,
  protos__chaincode_endorsement__field_indices_by_name,
  1,  protos__chaincode_endorsement__number_ranges,
  (ProtobufCMessageInit) protos__chaincode_endorsement__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protos__config_tree__field_descriptors[2] =
{
  {
    "channel_config",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protos__ConfigTree, channel_config),
    &common__config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resources_config",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Protos__ConfigTree, resources_config),
    &common__config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protos__config_tree__field_indices_by_name[] = {
  0,   /* field[0] = channel_config */
  1,   /* field[1] = resources_config */
};
static const ProtobufCIntRange protos__config_tree__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protos__config_tree__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protos.ConfigTree",
  "ConfigTree",
  "Protos__ConfigTree",
  "protos",
  sizeof(Protos__ConfigTree),
  2,
  protos__config_tree__field_descriptors,
  protos__config_tree__field_indices_by_name,
  1,  protos__config_tree__number_ranges,
  (ProtobufCMessageInit) protos__config_tree__init,
  NULL,NULL,NULL    /* reserved[123] */
};
